import Head from 'next/head'
import Hero from './components/Hero'
import Shop from './components/Shop'
import Discover from './components/Discover'
import Reviews from './components/Reviews'


export default function Home() {
  return (
    <>
      <Head>
        <title>The Corner Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Shop />
       <Discover />
       {/* <Reviews /> */}
        
      </main>
   
    </>
  )
}
